### ISSUE TITLE
import your vue-scrollbar, find error: cannot find module 'jade'

### ISSUE THREAD

**Issue by chasewoo** [BosNaufal/vue-scrollbar#9]
I use `vue-cli` to build this application.
When I import your `vue-scrollbar`, the terminal show this error.

```
Unhandled rejection Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/consolidate/lib/consolidate.js:324:34
    at /Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.jade.render (/Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/consolidate/lib/consolidate.js:320:10)
    at Object.module.exports (/Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/vue-loader/lib/template-loader.js:39:20)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/chaselwu/Developing/Codes/vitualreaty/vitual-process-site/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
```

**Comment by chasewoo** [comment]
I install jade-loader, but I forget to install jade. This problem is solved.
